# This is a basic workflow that is manually triggered

name: db_Revistas

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'ligacao'
        # Default value if no value is explicitly provided
        default: '---'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

      query:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Criar DB'
        # Default value if no value is explicitly provided
        default: 'revistas.sql'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  ligacao:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: db02

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v4
    - name: check folder
      run: ls -l
    - name: criar db
      run: mysql -h ${{ inputs.name}} -u ${{ secrets.USER }} -p ${{ secrets.PASS }} < ${{ github.event.inputs.query }}
